"""drop duplicate weather columns from activities

Revision ID: 0df6cafe31c3
Revises: 46dd70819f77
Create Date: 2026-09-24 16:58:45.463619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df6cafe31c3'
down_revision: Union[str, None] = '46dd70819f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'weather_pressure')
    op.drop_column('activities', 'weather_visibility')
    op.drop_column('activities', 'weather_feels_like_celsius')
    op.drop_column('activities', 'weather_humidity')
    op.drop_column('activities', 'weather_clouds')
    op.drop_column('activities', 'weather_wind_deg')
    op.drop_column('activities', 'weather_temp_celsius')
    op.drop_column('activities', 'weather_dew_point_celsius')
    op.drop_column('activities', 'weather_main')
    op.drop_column('activities', 'weather_uvi')
    op.drop_column('activities', 'weather_wind_speed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('weather_wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_uvi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_main', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_dew_point_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_temp_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_wind_deg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_clouds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_feels_like_celsius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_visibility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('weather_pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
