"""widen activities for raw_process notebook final df

Revision ID: 46dd70819f77
Revises: e9d39b48049e
Create Date: 2026-09-24 16:53:01.037932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46dd70819f77'
down_revision: Union[str, None] = 'e9d39b48049e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('raw_imported_at', sa.DateTime(), nullable=True))
    op.add_column('activities', sa.Column('activity_name', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('event_type', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('elapsed_duration_s', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('moving_duration_s', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('avg_power', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('norm_power', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('avg_stride_length', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('avg_vertical_oscillation', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('avg_vertical_ratio', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('avg_ground_contact_time', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('start_latitude', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('start_longitude', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('training_effect_label', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('vo2_max', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('hr_time_in_zone_1', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('hr_time_in_zone_2', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('hr_time_in_zone_3', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('hr_time_in_zone_4', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('hr_time_in_zone_5', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('power_time_in_zone_1', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('power_time_in_zone_2', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('power_time_in_zone_3', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('power_time_in_zone_4', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('power_time_in_zone_5', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('location', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('pace', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('weather_pressure', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_humidity', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_uvi', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_clouds', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_visibility', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_wind_speed', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_wind_deg', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_main', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('weather_temp_celsius', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_feels_like_celsius', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('weather_dew_point_celsius', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'weather_dew_point_celsius')
    op.drop_column('activities', 'weather_feels_like_celsius')
    op.drop_column('activities', 'weather_temp_celsius')
    op.drop_column('activities', 'weather_main')
    op.drop_column('activities', 'weather_wind_deg')
    op.drop_column('activities', 'weather_wind_speed')
    op.drop_column('activities', 'weather_visibility')
    op.drop_column('activities', 'weather_clouds')
    op.drop_column('activities', 'weather_uvi')
    op.drop_column('activities', 'weather_humidity')
    op.drop_column('activities', 'weather_pressure')
    op.drop_column('activities', 'pace')
    op.drop_column('activities', 'location')
    op.drop_column('activities', 'power_time_in_zone_5')
    op.drop_column('activities', 'power_time_in_zone_4')
    op.drop_column('activities', 'power_time_in_zone_3')
    op.drop_column('activities', 'power_time_in_zone_2')
    op.drop_column('activities', 'power_time_in_zone_1')
    op.drop_column('activities', 'hr_time_in_zone_5')
    op.drop_column('activities', 'hr_time_in_zone_4')
    op.drop_column('activities', 'hr_time_in_zone_3')
    op.drop_column('activities', 'hr_time_in_zone_2')
    op.drop_column('activities', 'hr_time_in_zone_1')
    op.drop_column('activities', 'vo2_max')
    op.drop_column('activities', 'training_effect_label')
    op.drop_column('activities', 'start_longitude')
    op.drop_column('activities', 'start_latitude')
    op.drop_column('activities', 'avg_ground_contact_time')
    op.drop_column('activities', 'avg_vertical_ratio')
    op.drop_column('activities', 'avg_vertical_oscillation')
    op.drop_column('activities', 'avg_stride_length')
    op.drop_column('activities', 'norm_power')
    op.drop_column('activities', 'avg_power')
    op.drop_column('activities', 'calories')
    op.drop_column('activities', 'moving_duration_s')
    op.drop_column('activities', 'elapsed_duration_s')
    op.drop_column('activities', 'event_type')
    op.drop_column('activities', 'activity_name')
    op.drop_column('activities', 'raw_imported_at')
    # ### end Alembic commands ###
