"""add session_version for password-change session invalidation

Revision ID: 72841a4c1fc6
Revises: 76387e6e2ff7
Create Date: 2026-09-17 23:22:14.295908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72841a4c1fc6'
down_revision: Union[str, None] = '76387e6e2ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill the existing row with a server default, then drop it --
    # new rows always set session_version via the model's Python default.
    op.add_column(
        'users', sa.Column('session_version', sa.Integer(), nullable=False, server_default='1')
    )
    op.alter_column('users', 'session_version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_version')
    # ### end Alembic commands ###
