"""drop csv columns from activities_raw, api-only now

Revision ID: 7607ad26d15e
Revises: 47829badf99e
Create Date: 2026-09-16 14:12:26.567636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7607ad26d15e'
down_revision: Union[str, None] = '47829badf99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_activities_raw_user_row_hash'), 'activities_raw', type_='unique')
    op.drop_column('activities_raw', 'training_stress_score')
    op.drop_column('activities_raw', 'avg_pace')
    op.drop_column('activities_raw', 'elapsed_time')
    op.drop_column('activities_raw', 'avg_vertical_ratio')
    op.drop_column('activities_raw', 'min_temp')
    op.drop_column('activities_raw', 'row_hash')
    op.drop_column('activities_raw', 'avg_vertical_oscillation')
    op.drop_column('activities_raw', 'favorite')
    op.drop_column('activities_raw', 'avg_gap')
    op.drop_column('activities_raw', 'body_battery_drain')
    op.drop_column('activities_raw', 'best_pace')
    op.drop_column('activities_raw', 'calories')
    op.drop_column('activities_raw', 'decompression')
    op.drop_column('activities_raw', 'moving_time')
    op.drop_column('activities_raw', 'max_power')
    op.drop_column('activities_raw', 'time')
    op.drop_column('activities_raw', 'total_ascent')
    op.drop_column('activities_raw', 'date')
    op.drop_column('activities_raw', 'steps')
    op.drop_column('activities_raw', 'max_run_cadence')
    op.drop_column('activities_raw', 'total_reps')
    op.drop_column('activities_raw', 'avg_stride_length')
    op.drop_column('activities_raw', 'number_of_laps')
    op.drop_column('activities_raw', 'total_sets')
    op.drop_column('activities_raw', 'best_lap_time')
    op.drop_column('activities_raw', 'avg_run_cadence')
    op.drop_column('activities_raw', 'normalized_power_np')
    op.drop_column('activities_raw', 'source_file')
    op.drop_column('activities_raw', 'activity_type')
    op.drop_column('activities_raw', 'title')
    op.drop_column('activities_raw', 'avg_hr')
    op.drop_column('activities_raw', 'aerobic_te')
    op.drop_column('activities_raw', 'max_temp')
    op.drop_column('activities_raw', 'min_elevation')
    op.drop_column('activities_raw', 'total_descent')
    op.drop_column('activities_raw', 'distance')
    op.drop_column('activities_raw', 'max_hr')
    op.drop_column('activities_raw', 'avg_power')
    op.drop_column('activities_raw', 'avg_ground_contact_time')
    op.drop_column('activities_raw', 'max_elevation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities_raw', sa.Column('max_elevation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_ground_contact_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_power', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('max_hr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('distance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('total_descent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('min_elevation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('max_temp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('aerobic_te', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_hr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('source_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('normalized_power_np', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_run_cadence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('best_lap_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('total_sets', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('number_of_laps', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_stride_length', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('total_reps', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('max_run_cadence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('steps', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('total_ascent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('max_power', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('moving_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('decompression', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('calories', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('best_pace', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('body_battery_drain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_gap', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('favorite', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_vertical_oscillation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('row_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('min_temp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_vertical_ratio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('elapsed_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('avg_pace', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities_raw', sa.Column('training_stress_score', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_activities_raw_user_row_hash'), 'activities_raw', ['user_id', 'row_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
