"""widen activities_raw for garmin api source

Revision ID: f8ebab229deb
Revises: 04f10496bec8
Create Date: 2026-09-15 17:47:16.558954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ebab229deb'
down_revision: Union[str, None] = '04f10496bec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill existing rows (all CSV-sourced so far) with a server
    # default, then drop it -- new rows always set `source` explicitly.
    op.add_column(
        'activities_raw',
        sa.Column('source', sa.String(), nullable=False, server_default='csv_upload'),
    )
    op.alter_column('activities_raw', 'source', server_default=None)
    op.add_column('activities_raw', sa.Column('garmin_activity_id', sa.Integer(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_activity_name', sa.String(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_activity_type', sa.String(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_event_type', sa.String(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_start_time_local', sa.String(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_start_time_gmt', sa.String(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_distance', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_duration', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_elapsed_duration', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_moving_duration', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_calories', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_bmr_calories', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_average_hr', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_max_hr', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_average_running_cadence', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_max_running_cadence', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_average_speed', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_max_speed', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_avg_grade_adjusted_speed', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_avg_power', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_max_power', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_norm_power', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_elevation_gain', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_elevation_loss', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_min_elevation', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_max_elevation', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_avg_stride_length', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_avg_vertical_oscillation', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_avg_vertical_ratio', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_avg_ground_contact_time', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_start_latitude', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_start_longitude', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_end_latitude', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_end_longitude', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_steps', sa.Integer(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_lap_count', sa.Integer(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_min_temperature', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_max_temperature', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_aerobic_training_effect', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_aerobic_training_effect_message', sa.String(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_anaerobic_training_effect', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_anaerobic_training_effect_message', sa.String(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_training_effect_label', sa.String(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_v_o2_max_value', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_difference_body_battery', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_hr_time_in_zone_1', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_hr_time_in_zone_2', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_hr_time_in_zone_3', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_hr_time_in_zone_4', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_hr_time_in_zone_5', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_power_time_in_zone_1', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_power_time_in_zone_2', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_power_time_in_zone_3', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_power_time_in_zone_4', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_power_time_in_zone_5', sa.Float(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_is_favorite', sa.Boolean(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_is_pr', sa.Boolean(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_device_id', sa.Integer(), nullable=True))
    op.add_column('activities_raw', sa.Column('api_manufacturer', sa.String(), nullable=True))
    op.alter_column('activities_raw', 'row_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_activities_raw_user_garmin_activity_id', 'activities_raw', ['user_id', 'garmin_activity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_activities_raw_user_garmin_activity_id', 'activities_raw', type_='unique')
    op.alter_column('activities_raw', 'row_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('activities_raw', 'api_manufacturer')
    op.drop_column('activities_raw', 'api_device_id')
    op.drop_column('activities_raw', 'api_is_pr')
    op.drop_column('activities_raw', 'api_is_favorite')
    op.drop_column('activities_raw', 'api_power_time_in_zone_5')
    op.drop_column('activities_raw', 'api_power_time_in_zone_4')
    op.drop_column('activities_raw', 'api_power_time_in_zone_3')
    op.drop_column('activities_raw', 'api_power_time_in_zone_2')
    op.drop_column('activities_raw', 'api_power_time_in_zone_1')
    op.drop_column('activities_raw', 'api_hr_time_in_zone_5')
    op.drop_column('activities_raw', 'api_hr_time_in_zone_4')
    op.drop_column('activities_raw', 'api_hr_time_in_zone_3')
    op.drop_column('activities_raw', 'api_hr_time_in_zone_2')
    op.drop_column('activities_raw', 'api_hr_time_in_zone_1')
    op.drop_column('activities_raw', 'api_difference_body_battery')
    op.drop_column('activities_raw', 'api_v_o2_max_value')
    op.drop_column('activities_raw', 'api_training_effect_label')
    op.drop_column('activities_raw', 'api_anaerobic_training_effect_message')
    op.drop_column('activities_raw', 'api_anaerobic_training_effect')
    op.drop_column('activities_raw', 'api_aerobic_training_effect_message')
    op.drop_column('activities_raw', 'api_aerobic_training_effect')
    op.drop_column('activities_raw', 'api_max_temperature')
    op.drop_column('activities_raw', 'api_min_temperature')
    op.drop_column('activities_raw', 'api_lap_count')
    op.drop_column('activities_raw', 'api_steps')
    op.drop_column('activities_raw', 'api_end_longitude')
    op.drop_column('activities_raw', 'api_end_latitude')
    op.drop_column('activities_raw', 'api_start_longitude')
    op.drop_column('activities_raw', 'api_start_latitude')
    op.drop_column('activities_raw', 'api_avg_ground_contact_time')
    op.drop_column('activities_raw', 'api_avg_vertical_ratio')
    op.drop_column('activities_raw', 'api_avg_vertical_oscillation')
    op.drop_column('activities_raw', 'api_avg_stride_length')
    op.drop_column('activities_raw', 'api_max_elevation')
    op.drop_column('activities_raw', 'api_min_elevation')
    op.drop_column('activities_raw', 'api_elevation_loss')
    op.drop_column('activities_raw', 'api_elevation_gain')
    op.drop_column('activities_raw', 'api_norm_power')
    op.drop_column('activities_raw', 'api_max_power')
    op.drop_column('activities_raw', 'api_avg_power')
    op.drop_column('activities_raw', 'api_avg_grade_adjusted_speed')
    op.drop_column('activities_raw', 'api_max_speed')
    op.drop_column('activities_raw', 'api_average_speed')
    op.drop_column('activities_raw', 'api_max_running_cadence')
    op.drop_column('activities_raw', 'api_average_running_cadence')
    op.drop_column('activities_raw', 'api_max_hr')
    op.drop_column('activities_raw', 'api_average_hr')
    op.drop_column('activities_raw', 'api_bmr_calories')
    op.drop_column('activities_raw', 'api_calories')
    op.drop_column('activities_raw', 'api_moving_duration')
    op.drop_column('activities_raw', 'api_elapsed_duration')
    op.drop_column('activities_raw', 'api_duration')
    op.drop_column('activities_raw', 'api_distance')
    op.drop_column('activities_raw', 'api_start_time_gmt')
    op.drop_column('activities_raw', 'api_start_time_local')
    op.drop_column('activities_raw', 'api_event_type')
    op.drop_column('activities_raw', 'api_activity_type')
    op.drop_column('activities_raw', 'api_activity_name')
    op.drop_column('activities_raw', 'garmin_activity_id')
    op.drop_column('activities_raw', 'source')
    # ### end Alembic commands ###
